version: "3.8"
services:
  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    container_name: zookeeper
    hostname: ${HOSTNAME}
    ports:
      - 2181:2181
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  hbase:
    build: 
      context: ./hbase
    container_name: hbase
    hostname: ${HOSTNAME}
    ports:
      - 16000:16000 # master
      - 16010:16010 # master-ui
      - 16020:16020 # rs
      - 16030:16030 # rs
      - 16201:16201 # rs
      - 16301:16301 # rs-ui
    volumes:
      - 'hbase_data:/hbase-data'
    depends_on:
      - zookeeper
volumes:
  kafka_data:
  zookeeper_data:
  hbase_data:
  aerospike_data:
